### ISSUE TITLE
ElectronWMD i386 version

### ISSUE THREAD

**Issue by jptheguit** [asivery/ElectronWMD#1]
easy to install without problem on my small PC (eeepc asus with 2g memory and SSD 250 et windows 7 Pro)
but impossible to connect with Sony MZ N707 or Sony MZ RH 910. I use my 2 HI MD (MZ RH 910 et MZ RH1) on this PC with Sonic Stage Ultimate 4,3 version and I don't install Zadig Drivers.
Is it the problem or something else?

**Comment by asivery** [comment]
@jptheguit As this is the same bug as the one described in #2 , it should be fixed now. Please let me know if the issue persists.

**Comment by jptheguit** [comment]
I install the 0.11-0.2.7-win_ia32exe on my small PC test with my Sony MZ-N707 the transfert from mp3 works and the upload in SP too , seem to be slow , i will compare with chrome and webminidisc.
