### ISSUE TITLE
mac_arm64 version doesn't work at all

### ISSUE THREAD

**Issue by ZeroOnions** [asivery/ElectronWMD#11]
System says it's damaged, tried on M1 Max with Ventura.

**Comment by asivery** [comment]
@ZeroOnions, please check if the new instructions by @DaveFlashNL in the readme help with this - as I don't have an M1 Mac I can't really test the app. If the problem still persists, please let me know.

**Comment by ZeroOnions** [comment]
@asivery thanks for the info - de-quarantining the app helped and the arm64 version launched and connected without issues.
