### ISSUE TITLE
1.4.0? :-)

### ISSUE THREAD

**Issue by ghost** [asivery/ElectronWMD#15]
Not an issue - just hoping to see the newest update in Elektron form ;)

**Comment by zhanun** [comment]
1.4.0☺

**Comment by asivery** [comment]
@ZeroOnions @zhanun ElectronWMD 0.3.0-1.4.1 will be released in the next few days :)

**Comment by zhanun** [comment]
THX

**Comment by asivery** [comment]
Took longer than expected, but it's finally done.
