### ISSUE TITLE
Hide menubar

### ISSUE THREAD

**Issue by SammysHP** [asivery/ElectronWMD#16]
Right now the electron app shows the default menubar at the top with useless items (reload, set default download directory etc). Would it be possible to hide it? I've found several workarounds for different versions of Electron, but I'm not that familiar with the Electron framework.

**Comment by asivery** [comment]
Hi there @SammysHP!
It certainly is possible to hide the menu bar - you need to comment out these two lines:

https://github.com/asivery/ElectronWMD/blob/master/src/main.ts#L116-L117

Feel free to do it on a local copy of ElectronWMD. The menu bar, however, is a feature and not a bug, and the options it presents are crucial for the app. I am planning to move them to the 'Settings' dialog of WMD in due time, however I don't have that much free time right now, so the menu has to stay.

**Comment by SammysHP** [comment]
Oh sorry, I thought it was the default menu that's not relevant for ElectronWMD. If it's a feature, that's absolutely fine.
