### ISSUE TITLE
Unable to convert audio on Win10

### ISSUE THREAD

**Issue by bagelbyheart** [asivery/ElectronWMD#2]
Any attempt to convert WAV or FLAC audio fails with an error message about missing C:\Users\steph\AppData\Local\Programs\electronwmd\resources\...\node-encrypt-worker.js but there are only three files in that directory and no folders. I'm not sure how to proceed and the FAQ doesn't make it clear.

![image](https://user-images.githubusercontent.com/3092127/137665284-e18d6d0d-dd46-404f-beb2-ee0e4ae5cd6a.png)

**Comment by asivery** [comment]
@bagelbyheart I'm very sorry it took so long. I was able to replicate and fix the bug. You can try the new release out.

**Comment by bagelbyheart** [comment]
Yo! Tested and working! @asivery thank you so much!
