### ISSUE TITLE
v0.3.2-1.4.2 - white app window on mac

### ISSUE THREAD

**Issue by 0023-119** [asivery/ElectronWMD#21]
On mac_arm64 version, macOS Sonoma, after de-quarantining and self-signing - it runs, but instead of user interface all I get is just a white screen inside the app window.
Getting back to v0.3.1-1.4.2 solves the issue.

**Comment by asivery** [comment]
@0023-119 Please let me know if that fixed it. I've updated the Mac release.

**Comment by 0023-119** [comment]
It runs fine now :)
