### ISSUE TITLE
Unable to doiwnload a usable Mac ARM version.

### ISSUE THREAD

**Issue by baregills** [asivery/ElectronWMD#25]
When trying to open the app the system cannot use the software, which it states is damaged.
I downloaded the X64 version and it works perfectly on my Mac Studio M1 system.
I did see an earlier issue relating to an M2 Mac but I did not understand the suggested remedy, but as the X64 version worked I thought it may not be appropriate anyway.

**Comment by asivery** [comment]
Hello @baregills - Did you try to follow the steps described in the README?

**Comment by baregills** [comment]
I did and was not successful.
I concede that was likely a result of my limited understanding of the problem but since I then found that the X86 version works, I left it at that.

**Comment by asivery** [comment]
@baregills Interesting - I might have uploaded a corrupted version. Can you try again now? I tested the ARM version on a Mac yesterday, and it worked.

**Comment by baregills** [comment]
OK. Will do.

**Comment by asivery** [comment]
@baregills I'm sorry I can't see what you sent / attached.

**Comment by baregills** [comment]
How strange.

￼

I have attached it again.
In case it doesn’t work again, it is a small popup window saying that the program is damaged, can’t be opened and it should be moved to the trash.
It’s the same message I got when I reported the problem.

I do open non signed applications quite often and I have never had this issue. As the X86 version runs without a problem I can continue with that anyway.

**Comment by asivery** [comment]
@baregills I got the same error when I tested yesterday. I ran: `xattr -d com.apple.quarantine "/path/to/your.app"` and `codesign --sign - --force --deep "/path/to/your.app"`, and that solved the issue. Would you mind testing that?

**Comment by baregills** [comment]
Yes.
That worked.

😁

Thanks.

**Comment by asivery** [comment]
Great, thanks!
