### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by jptheguit** [asivery/ElectronWMD#4]
with the last version ;
![Capture_d_écran_15_04_2022_15_27](https://user-images.githubusercontent.com/91957199/163606193-26b12a2a-39d8-4e17-b94e-713a3dbbbdcd.jpg)

error :cannot find module 'jsbi'

**Comment by jptheguit** [comment]
And when I try electronwmd-0.1.2-0.2.7-mac_x64.dmg it works!!!!

**Comment by asivery** [comment]
@jptheguit Thanks for letting me know. I'm working on it

**Comment by asivery** [comment]
@jptheguit Please let me know if the issue persists on the newest release.

**Comment by jptheguit** [comment]
@asivery : the last release work , I have to reload once cause i have an "no more place" message. I upload one title, then 2 more ,then 4 more and no problem till the end. I use a Sony MZ -N910 with my old Mac (end 2011 with High Sierra)
I will try a new upload next morning. Good job
![Electron_WMD](https://user-images.githubusercontent.com/91957199/165462778-25464eb5-65c5-41ff-99a1-6d3b940626d7.jpg)

**Comment by asivery** [comment]
Thanks for the info, I'll what I can do

**Comment by asivery** [comment]
@jptheguit I'm so sorry for the delay. I managed to find the bug. I'll release the fixed version soon.

**Comment by jptheguit** [comment]
Thanks for your job. Do you think that a solution will be possible for Hi MD and Mac?

Envoyé de mon iPhone

**Comment by asivery** [comment]
It should work for MacOS.
As for HiMD, it is possible to add this functionality here (but not to the chrome version of WMD), but requires a ton of extra work I haven't done yet.

**Comment by asivery** [comment]
@jptheguit I have released the new version. Please let me know if all the issues have been resolved.

**Comment by jptheguit** [comment]
First try for the last version and everything seems ok . Thanks Asyvery
![Electron_WMD](https://user-images.githubusercontent.com/91957199/177102083-629c0f53-1126-4a2b-9805-ad4967272ab4.jpg)
![Electron_WMD2](https://user-images.githubusercontent.com/91957199/177102102-633075c4-7ccb-43b7-bf24-01efdd3ea7f0.jpg)

**Comment by asivery** [comment]
Glad it finally works, sorry it took so long.
