### ISSUE TITLE
[Question] Used the Song Recognition - Added un-removable stuff to TOC

### ISSUE THREAD

**Issue by jadehawk** [asivery/ElectronWMD#9]
Hi, 
I used the "Song recognition" to populate the songs on the minidisc, It found all tracks with no problem. I wanted to use the "Artist - Track" Layout. Upon writing the tracks to disc some tracks where named weird.  Look at track 5 and 6 of this image (attempted to Highlight the unwanted part).
![Track name](https://user-images.githubusercontent.com/333657/198246699-78ad6be8-239d-4ec7-b42d-b1c4bec7ff34.jpg)

In the MD Player display the track name displays correctly, but on the ElectromWMD or Web MiniDisc Pro it shows what you see on the picture.

If I delete or rename the track, the first part before the "/" does not go away. Tracks 5 & 6 Do not display a title on the MD Players screen yet you see what ElectonWMD seen on the picture.
![Track name 2](https://user-images.githubusercontent.com/333657/198246816-331279db-27f9-4c6f-8a08-060397df5dff.jpg)

Is it a bug? Did I do something wrong? how do I delete the entire track name to show untitle on ElectronWMD Screen. 

Recorder is : Sony MZ-NF610
ElectronWMD Version: 1.3.2
OS: Windows 11

P.S.
Rescanned songs and selected only title to be written. This is what I Got. Tracks 5,6,10,11 (10 and 11 where also affected earlier just didn't show up on the screen shot)
![No artists](https://user-images.githubusercontent.com/333657/198250272-08299ed2-85d7-416c-b5d2-aac5cc64aecf.jpg)

I also restarted PC and MD Player (No battery , Just unplugged Power Supply). No change.

Also Edited Track name on MD player itself. No change when loading to ElectronWMD

**Comment by jadehawk** [comment]
Fixed it by exporting to CSV and removing the weird stuff it added, Then reimported the edited CSV file.
Also found out it doesn't like "," commas in the title name (track 10).

CSV with bad entries added.
[VA - Music Mix (Bad).csv](https://github.com/asivery/ElectronWMD/files/9878321/VA.-.Music.Mix.Bad.csv)

Leaving open for @asivery to close, incase this is an actual bug.

**Comment by asivery** [comment]
Thanks for reporting both of these bugs, @jadehawk :)
I'll try to resolve them and I'll get back to you.

**Comment by asivery** [comment]
I forgot about this issue, sorry. This additional title is called the 'full-width title', and it's used to store kanji titles of songs and groups. I am not sure why WMD deemed it necessary to enable it for your disc, but due to the age of this issue, and the fact that the code responsible for those titles has changed several times, I'm closing it. If you encounter this problem again, please reopen this issue.
